name = "Solid"
license = "MIT"
licenselink = "https://github.com/podocarp/hugo-solid-theme/blob/master/LICENSE"
description = "A soldi theme for hugo."
homepage = ""
tags = [solid, blog, clean, minimal]
features = []
min_version = "0.41"

[author]
  name = "J. XD"
  homepage = ""